### PR TITLE
Bugfix: set output method fallback to console correctly.

### PR DESCRIPTION
**Pull request by alexeyklyukin**
By https://github.com/pheanex

### CODE REVIEW

**Comment by alexeyklyukin** [comment]
👍

**Comment by alexeyklyukin** [comment]
I've created the commit with the same contents and author on top of the current master branch, as merging it, given that the original file has been deleted and its contents split over multiple other ones, is not something I know how to do #76

**Comment by alexeyklyukin** [comment]
👍

**Comment by alexeyklyukin** [comment]
👍

**Comment by pheanex** [comment]
I also fixed this bug with #81 => Maybe its easier to take the fix/patch from there since i rebased the other branch on master.

**Comment by alexeyklyukin** [comment]
Yes, thank you, I'm closing this one.

**Pull request closed without merging**
