### PR TITLE
Add property `wal_directory`

### PR DESCRIPTION
**Pull request by erthalion**
Add property `wal_directory` to find a proper place of wal files based
on Postgesql version. Related to #83

### CODE REVIEW

**Comment by alexeyklyukin** [comment]
👍

**Comment by erthalion** [comment]
:+1:

**Comment by erthalion** [comment]
:+1:

**Comment by CyberDem0n** [comment]
:+1:

**Comment by alexeyklyukin** [comment]
merged, @erthalion thank you!

**Pull request merged**
