### PR TITLE
Match title line with underline

### PR DESCRIPTION
**Pull request by pheanex**
http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#sections

### CODE REVIEW

**Comment by hjacobs** [comment]
@pheanex are you on a [Stakkenblochen](https://www.youtube.com/watch?v=zqAdxN1IWQQ) tour through all our repos? :smirk:

**Comment by hjacobs** [comment]
:+1:

**Comment by pheanex** [comment]
In ten years from now I wanna be able to say: "2017! I was at the great Stakkenblochen-zalando-tour."
Let's make alignment great again! ;-)

**Comment by LappleApple** [comment]
👍

**Comment by LappleApple** [comment]
@pheanex I'm American, and I approve of this message. :)

**Comment by alexeyklyukin** [comment]
Thanks, please, don't merge it yet, as it will conflict with the much bigger change being currently in review. 

@LappleApple I can not find a "dontmerge" label, and I don't see a  dialog to create one for this repository, could you, please, create such a label?

**Comment by LappleApple** [comment]
@alexeyklyukin I created and applied the label. To make new labels, you have to go to the main "Issues" page.

**Comment by alexeyklyukin** [comment]
@LappleApple I was confused by the UI, it actually has 2 objects labelled "label" (a button and a drop-down list) on the issues page.  Thanks a lot!

**Comment by alexeyklyukin** [comment]
👍

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
