### PR TITLE
Create MAINTAINERS

### PR DESCRIPTION
**Pull request by LappleApple**
Here's a maintainers file :)

### CODE REVIEW

**Comment by alexeyklyukin** [comment]
👍

**Comment by alexeyklyukin** [comment]
@LappleApple Please, put your +1 as well :-)

**Comment by LappleApple** [comment]
Done :)

**Comment by alexeyklyukin** [comment]
@LappleApple please, put it to the comments for the pull-request, and not to my specific comment.

**Comment by LappleApple** [comment]
👍

**Comment by LappleApple** [comment]
👍

**Comment by alexeyklyukin** [comment]
👍

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
