### PR TITLE
Ensure we can read the version of PostgreSQL 10

### PR DESCRIPTION
**Pull request by feikesteenbergen**
Ensure we can read the version of PostgreSQL > 9.6

### CODE REVIEW

**Comment by a1exsh** [comment]
@feikesteenbergen Neat.  What's with that Change-id, a custom header from some exotic git/github client?

**Comment by feikesteenbergen** [comment]
@a1exsh the Change-Id is a gerrit thing: https://git.eclipse.org/r/Documentation/user-changeid.html
It's a commit message hook, which I've now removed for this repo ;-)

**Comment by alexeyklyukin** [comment]
@feikesteenbergen Thanks! I'm planning on merging in the big one (https://github.com/zalando/pg_view/pull/74) first and then resolving conflicts with your change. Hopefully with PG 10 it's not yet production-critical :-)

**Comment by alexeyklyukin** [comment]
👍

**Comment by alexeyklyukin** [comment]
I've created the commit with the same contents and author on top of the current master branch, as merging it, given that the original file has been deleted and its contents split over multiple other ones, is not something I know how to do. https://github.com/zalando/pg_view/pull/78

**Pull request closed without merging**
