### PR TITLE
Connect using Connection Service File

### PR DESCRIPTION
**Pull request by feikesteenbergen**
For those who already have their Connection Service Files setup, it is useful not to have
to specify the configuration file.
By connection using the service=<name> format we delegate all the resolving of service file
locations to libpq.

### CODE REVIEW

**Comment by a1exsh** [comment]
:+1:

**Comment by LappleApple** [comment]
@a1exsh @alexeyklyukin Is it ok to update the branch and then merge?

**Comment by feikesteenbergen** [comment]
I can't update this branch myself anymore, should I close and reopen a PR to rebase?

**Comment by LappleApple** [comment]
@feikesteenbergen I can update it if @alexeyklyukin approves it, I have admin SUPERPOWERS

**Comment by LappleApple** [comment]
@alexeyklyukin Hey can we move forward with @feikesteenbergen's PR?

**Comment by alexeyklyukin** [comment]
@feikesteenbergen it needs to be updated to change pg_view/__init.py__ instead of pg_view.py, as I don't know the way to do it via conflict resolution (the main pg_view.py is split into multiple files). If you have time to do it - please, do, otherwise I will take care of it.

**Pull request closed without merging**
